Repository AdaptiveMotorControlLab/CellSeg3D, pull requests merged in 2022-07, with the labels that each got.

#14 Added more anisotropy handling + fix global in review
  .gitignore
  .napari/DESCRIPTION.md
  README.md
  docs/res/logo/logo_alpha.png
  docs/res/logo/logo_background.png
  napari_cellseg3d/_tests/test_review.py
  napari_cellseg3d/interface.py
  napari_cellseg3d/launch_review.py
  napari_cellseg3d/model_framework.py
  napari_cellseg3d/model_instance_seg.py
  napari_cellseg3d/model_workers.py
  napari_cellseg3d/plugin_base.py
  napari_cellseg3d/plugin_crop.py
  napari_cellseg3d/plugin_dock.py
  napari_cellseg3d/plugin_helper.py
  napari_cellseg3d/plugin_metrics.py
  napari_cellseg3d/plugin_model_inference.py
  napari_cellseg3d/plugin_model_training.py
  napari_cellseg3d/plugin_review.py
  napari_cellseg3d/plugin_utilities.py
  napari_cellseg3d/res/logo_alpha.png
  napari_cellseg3d/setup.py
  napari_cellseg3d/utils.py
  tox.ini
Labels: enhancement, fix

#17 [WIP] UI API overhaul + several features/fixes
  .gitignore
  README.md
  docs/conf.py
  docs/res/code/interface.rst
  docs/res/guides/convert_module_guide.rst
  docs/res/guides/cropping_module_guide.rst
  docs/res/guides/review_module_guide.rst
  docs/res/logo/logo_alpha.png
  napari_cellseg3d/_tests/test_review.py
  napari_cellseg3d/interface.py
  napari_cellseg3d/launch_review.py
  napari_cellseg3d/model_framework.py
  napari_cellseg3d/plugin_base.py
  napari_cellseg3d/plugin_convert.py
  napari_cellseg3d/plugin_crop.py
  napari_cellseg3d/plugin_dock.py
  napari_cellseg3d/plugin_helper.py
  napari_cellseg3d/plugin_metrics.py
  napari_cellseg3d/plugin_model_inference.py
  napari_cellseg3d/plugin_model_training.py
  napari_cellseg3d/plugin_review.py
  napari_cellseg3d/utils.py
  requirements.txt
  setup.cfg
Labels: enhancement, fix

#24 Improved pretrained weights usage
  napari_cellseg3d/log_utility.py
  napari_cellseg3d/model_workers.py
  napari_cellseg3d/models/model_SegResNet.py
  napari_cellseg3d/models/model_TRAILMAP.py
  napari_cellseg3d/models/model_VNet.py
  napari_cellseg3d/plugin_model_inference.py
  napari_cellseg3d/plugin_model_training.py
  napari_cellseg3d/utils.py
Labels: enhancement

#16 v0.0.1rc3
  napari_cellseg3d/__init__.py
  napari_cellseg3d/plugin_helper.py
  setup.cfg
Labels: versioning
