Repository AdaptiveMotorControlLab/CellSeg3D, pull requests merged in 2022-08, with the labels that each got.

#27 Timer improvement
  napari_cellseg3d/plugin_dock.py
  napari_cellseg3d/utils.py
Labels: enhancement, UI

#26 Inference on layer
  napari_cellseg3d/interface.py
  napari_cellseg3d/model_instance_seg.py
  napari_cellseg3d/model_workers.py
  napari_cellseg3d/models/model_TRAILMAP.py
  napari_cellseg3d/plugin_model_inference.py
  napari_cellseg3d/utils.py
  setup.cfg
Labels: enhancement, UI

#12 [WIP] Adding SwinUNetR
  .gitignore
  napari_cellseg3d/interface.py
  napari_cellseg3d/model_framework.py
  napari_cellseg3d/model_workers.py
  napari_cellseg3d/models/model_SegResNet.py
  napari_cellseg3d/models/model_SwinUNetR.py
  napari_cellseg3d/models/model_TRAILMAP.py
  napari_cellseg3d/models/model_VNet.py
  napari_cellseg3d/models/pretrained/pretrained_model_urls.json
  napari_cellseg3d/plugin_model_inference.py
  napari_cellseg3d/plugin_model_training.py
  napari_cellseg3d/utils.py
  requirements.txt
  setup.cfg
Labels: enhancement, ML

#29 v0.0.1rc4
  napari_cellseg3d/__init__.py
  napari_cellseg3d/plugin_helper.py
  setup.cfg
Labels: versioning
