Repository AdaptiveMotorControlLab/CellSeg3D, pull requests merged in 2024-05, with the labels that each got.

#69 Small inference docs update
  docs/source/guides/inference_module_guide.rst
  docs/source/images/inference_results_example.png
Labels: documentation

#66 Fix setup.cfg name
  .github/workflows/test_and_deploy.yml
  setup.cfg
Labels: fix

#78 Add demo instructions
  README.md
Labels: documentation

#72 Update macbook conda
  README.md
  conda/napari_CellSeg3D_ARM64.yml
  docs/source/guides/detailed_walkthrough.rst
  docs/source/guides/inference_module_guide.rst
  docs/source/guides/installation_guide.rst
  docs/source/guides/review_module_guide.rst
  docs/source/guides/training_module_guide.rst
  docs/source/guides/utils_module_guide.rst
  docs/welcome.rst
  pyproject.toml
Labels: conda, ready to merge

#70 Small API changes for training
  .napari/DESCRIPTION.md
  .napari/config.yml
  README.md
  docs/_config.yml
  docs/source/guides/custom_model_template.rst
  docs/source/guides/detailed_walkthrough.rst
  docs/source/guides/installation_guide.rst
  docs/source/guides/training_wnet.rst
  examples/README.md
  napari_cellseg3d/_tests/test_plugin_inference.py
  napari_cellseg3d/_tests/test_plugin_training.py
  napari_cellseg3d/_tests/test_plugin_utils.py
  napari_cellseg3d/_tests/test_training.py
  napari_cellseg3d/code_models/models/pretrained/pretrained_model_urls.json
  napari_cellseg3d/code_models/models/wnet/model.py
  napari_cellseg3d/code_models/worker_inference.py
  napari_cellseg3d/code_models/worker_training.py
  napari_cellseg3d/code_plugins/plugin_helper.py
  napari_cellseg3d/code_plugins/plugin_model_inference.py
  napari_cellseg3d/code_plugins/plugin_model_training.py
  napari_cellseg3d/config.py
  napari_cellseg3d/dev_scripts/classifier_test.ipynb
  napari_cellseg3d/dev_scripts/colab_training.py
  napari_cellseg3d/dev_scripts/test_new_evaluation.ipynb
  notebooks/colab_wnet_training.ipynb
  pyproject.toml
Labels: ML, wandb

#79 update training of WNet3D
  notebooks/Colab_WNet3D_training.ipynb
  notebooks/colab_wnet_training.ipynb
  notebooks/train_wnet.ipynb
Labels: enhancement, colab

#80 Colab demo : Inference
  README.md
  examples/c5image.tif
  napari_cellseg3d/dev_scripts/remote_inference.py
  notebooks/colab_inference_demo.ipynb
Labels: colab
